[package]
name = "pl0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]

[features]
trace_lexer = []
trace_parser = []
trace_opcode = []
